// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-xaZZf-Lqqxztmqc9Swykjj5nLr6nHA',
    appId: '1:37460275644:web:fb55c7d9309c2b90aafbb9',
    messagingSenderId: '37460275644',
    projectId: 'artistryhub-d82a4',
    authDomain: 'artistryhub-d82a4.firebaseapp.com',
    storageBucket: 'artistryhub-d82a4.firebasestorage.app',
    measurementId: 'G-S7H7VDNDJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4QgbEPZ883yYsyqfQV3arIC7yrq9VbOw',
    appId: '1:37460275644:android:374e3fecfa3311c9aafbb9',
    messagingSenderId: '37460275644',
    projectId: 'artistryhub-d82a4',
    storageBucket: 'artistryhub-d82a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmCvdIH2D0JX_McpALdu7igtVbRekVKg',
    appId: '1:37460275644:ios:c55e08bfe2a9a606aafbb9',
    messagingSenderId: '37460275644',
    projectId: 'artistryhub-d82a4',
    storageBucket: 'artistryhub-d82a4.firebasestorage.app',
    iosBundleId: 'com.example.artistryHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATmCvdIH2D0JX_McpALdu7igtVbRekVKg',
    appId: '1:37460275644:ios:c55e08bfe2a9a606aafbb9',
    messagingSenderId: '37460275644',
    projectId: 'artistryhub-d82a4',
    storageBucket: 'artistryhub-d82a4.firebasestorage.app',
    iosBundleId: 'com.example.artistryHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa-xaZZf-Lqqxztmqc9Swykjj5nLr6nHA',
    appId: '1:37460275644:web:483f4d612089b3d2aafbb9',
    messagingSenderId: '37460275644',
    projectId: 'artistryhub-d82a4',
    authDomain: 'artistryhub-d82a4.firebaseapp.com',
    storageBucket: 'artistryhub-d82a4.firebasestorage.app',
    measurementId: 'G-7HMCMMRNHD',
  );
}
